### ISSUE TITLE
Trait bound `ThreadRng: rand_core::RngCore` is not satisfied

### ISSUE THREAD

**Issue by mellowCS** [CryptArchy/regex_generate#4]
Hi,

I'm trying to implement the example given in the ReadMe. However, I cannot use *rand::thread_rng()* as I get the following error:

```
the trait bound `ThreadRng: rand_core::RngCore` is not satisfied
required because of the requirements on the impl of `rand::Rng` for `ThreadRng`
```
I first used rand version <mark>0.8.3</mark> and then went back to <mark>0.8</mark> to have the same version as in the example. I also use regex_generate version <mark>0.2</mark> and run the rust compiler stable version <mark>1.49.0</mark>.

This is my code (basically the same as the example with a different regex and max repeat):

```
extern crate regex_generate;
extern crate rand;

use regex_generate::Generator;

fn main() {
    let mut gen = Generator::new(r"(a|b|c)*", rand::thread_rng(), 3).unwrap();
    let mut buffer = vec![];
    gen.generate(&mut buffer).unwrap();
    let output = String::from_utf8(buffer).unwrap();

    println!("Random Date: {}", output);
}
```
I hope you can somehow reproduce this problem.

**Comment by azdle** [comment]
The version of `regex_generate` on crates hasn't been updated to `rand` 0.8 yet. You can either use `rand` 0.7 or use the version of `regex_generate` from git.

**Comment by mellowCS** [comment]
@azdle Thank you, it's working now.
